version: "3.5"
services:
  sequencer:
    build:
      context: sequencer
      args:
        UPSTREAM_VERSION: v4.2.0
        DATA_DIRECTORY: /data
    volumes:
      - sequencer-data:/data
      - keystore-data:/keystore
    environment:
      KEY_STORE_DIRECTORY: /keystore
      DATA_DIRECTORY: /data
      AZTEC_RESET_ADMIN_API_KEY: ""
      GOVERNANCE_PROPOSER_PAYLOAD_ADDRESS: ""
      P2P_MAX_PEERS: ""
      L1_GAS_LIMIT_BUFFER_PERCENTAGE: ""
      L1_GAS_PRICE_MAX: ""
      L1_BLOB_FEE_PER_GAS_MAX: ""
      L1_PRIORITY_FEE_BUMP_PERCENTAGE: ""
      L1_PRIORITY_FEE_RETRY_BUMP_PERCENTAGE: ""
      L1_MINIMUM_PRIORITY_FEE_PER_GAS_GWEI: ""
      SEQ_MAX_TX_PER_CHECKPOINT: ""
      SEQ_BLOCK_DURATION_MS: ""
      SEQ_BUILD_CHECKPOINT_IF_EMPTY: ""
      SEQ_L1_PUBLISHING_TIME_ALLOWANCE_IN_SLOT: ""
      VALIDATOR_MAX_L2_BLOCK_GAS: ""
      VALIDATOR_MAX_DA_BLOCK_GAS: ""
      VALIDATOR_MAX_TX_PER_BLOCK: ""
      VALIDATOR_MAX_TX_PER_CHECKPOINT: ""
      LOG_LEVEL: info
      EXTRA_OPTS: ""
    restart: unless-stopped
volumes:
  sequencer-data: {}
  keystore-data: {}
